# Generated by Django 2.2 on 2020-05-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=70, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('isin', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('fk_mutual_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutual_funds.MutualFunds')),
            ],
            options={
                'unique_together': {('fk_mutual_fund', 'date')},
            },
        ),
    ]
